language: ruby

before_install:
  - sudo apt update
  - sudo apt install -y inkscape pdf2svg

script: make check

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# cache: bundler # caching bundler gem packages will speed up build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  target_branch: gh-pages
  keep_history: false
  verbose: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
