dist: bionic    # Ubuntu 18.04 LTS
language: ruby

# clone full git history for git-restore-mtime to work
git:
  depth: false

before_install:
  - sudo apt update
  - sudo apt install -y inkscape pdf2svg
  - git clone https://github.com/MestreLion/git-tools # Distro version is currently broken

script: 
  - ./git-tools/git-restore-mtime
  - make check

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  bundler: true               # Enable caching of bundler gem packages
  directories:
  - $TRAVIS_BUILD_DIR/.cache  # Enable caching link checks
  - $TRAVIS_BUILD_DIR/assets/infographics  # Enable caching of generated infographics

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  target_branch: gh-pages
  keep_history: false
  verbose: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
