# Site settings
url: https://faktaoklimatu.cz
email: info@faktaoklimatu.cz
twitter: "faktaoklimatu"
newsletter: "https://tinyletter.com/faktaoklimatu/subscribe"
fundraising: "https://www.darujme.cz/projekt/1203742"
author: faktaoklimatu.cz
description: Shromažďujeme data o klimatu a klimatické změně, která poskytují vědecké instituce a zpracováváme z nich grafy a infografiky pro další použití.
keywords: klima, změna klimatu, infografiky

include: [ ".well-known" ]
exclude:
    - README.md
    - AUTHORS.md           # Authors file
    - Gemfile              # Build settings
    - Gemfile.lock         # Build settings
    - Makefile             # Build settings
    - utils                # Development files
    - Dockerfile           # Containerization
    - _infografiky/*/*.pdf # Original infographics (build moves them to assets)
    - _studie/*.jpg        # Study images
    - _studie/*.png        # Study images
    - _studie/*.pdf        # Original study infographics (build moves them to assets)
collections:
    infografiky:
        output: true
        permalink: /:collection/:title
    sekce:
        output: false
        permalink: /:collection/:title
    stranky:
        output: true
        permalink: /:title
    studie:
        output: true
        permalink: /:collection/:title
    explainery:
        output: true
        permalink: /:collection/:title
    datasety:
        output: true
        permalink: /:collection/:title
    rozcestniky:
        output: true
        permalink: /:collection/:title
sass:
    sass_dir: assets/_scss
    style: compressed
cache_dir: .cache
force_polling: true    # Force polling to resolve Windows issues with watch

cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    css_hash:         "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    js:               "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    js_hash:          "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    jquery:           "https://code.jquery.com/jquery-3.2.1.slim.min.js"
    jquery_hash:      "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    popper_hash:      "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    fa:               "https://use.fontawesome.com/releases/v5.3.1/css/all.css"
    fa_hash:          "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
    tocbot:           "https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.11.1/tocbot.min.js"
    tocbot_hash:      "sha384-TnuMTlegqfBi40E9e3dO2qfmPVKDjLFCCgyZ5bR3SA/hYTJXI090bTbAr/AXO+bc"

# Enable smart quotes
kramdown:
    smart_quotes: sbquo,lsquo,bdquo,ldquo

markdown: FaktaOKlimatuProcessor

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-last-modified-at

target-blank:
    add_css_classes: ext-link

jekyll-archives:
  enabled: [ "tags" ]
  layouts:
    tag: tag
  permalinks:
    tag: '/temata/:name/'
  collections:
    merge_tags: true
